services:
  app:
    build:
      context: .
    command: sh -c "rm -f /app/tmp/sockets/puma.sock tmp/pids/server.pid &&
      bundle exec rails db:prepare &&
      bin/dev "
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/parking_management_development
      NGROK_HOST: ${NGROK_HOST:-}
    tty: true
    stdin_open: true

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
  bundle:
  node_modules:
