FROM node:23-slim AS nodejs

FROM ruby:3.3.0-slim

ARG RAILS_MASTER_KEY # アセットコンパイル時に必要(credentials.yml.enc を復号化するために必要なキー)

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    libyaml-dev \
    vim \
    && rm -rf /var/lib/apt/lists/*

COPY --from=nodejs /usr/local /usr/local

COPY Gemfile Gemfile.lock ./
RUN bundle config set --local without 'development test' && \
    bundle install

COPY package.json yarn.lock* ./
RUN npm install

COPY . .

RUN RAILS_ENV=production \
    RAILS_MASTER_KEY=${RAILS_MASTER_KEY} \
    SECRET_KEY_BASE=dummy \
    rails assets:precompile && \
    rm -rf tmp/cache

CMD ["bin/rails", "server", "-b", "0.0.0.0"]